// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace traveldesk.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Multiple", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<string>("authorized_by")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("company_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("debited_to")
                        .HasColumnType("longtext");

                    b.Property<int>("emp_id")
                        .HasColumnType("int");

                    b.Property<string>("file_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("file_size")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("inv_rec_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("invoice")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("invoiceType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("invoice_number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("remark")
                        .HasColumnType("longtext");

                    b.Property<string>("statement")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("vendor_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("multiples");
                });
#pragma warning restore 612, 618
        }
    }
}
